name = "ProteinChains"
uuid = "b8e8f2a5-48d3-44f1-ba0d-c71cb7726ff8"
authors = ["Anton Oresten <anton.oresten42@gmail.com> and contributors"]
version = "0.7.6"

[deps]
AssigningSecondaryStructure = "8ed43e74-60fb-4e11-99b9-91deed37aef7"
Backboner = "9ac9c2a2-1cfe-46d3-b3fd-6fa470ea56a7"
BioStructures = "de9282ab-8554-53be-b2d6-f6c222edabfc"
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DynamicStructs = "e139c391-eeee-4818-b359-c8725224fb1f"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
InlineStrings = "842dd82b-1e85-43dc-bf29-5d0ee9dffc48"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PeriodicTable = "7b2266bf-644c-5ea3-82d8-af4bbd25a884"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
AssigningSecondaryStructure = "0.5"
Backboner = "0.12"
BioStructures = "4"
BitIntegers = "0.3.4"
Compat = "4"
DynamicStructs = "0.2.3"
Graphs = "1"
HDF5 = "0.17"
InlineStrings = "1.4.3"
JLD2 = "0.5, 0.6"
JSON = "0.21"
LinearAlgebra = "1"
PeriodicTable = "1"
Reexport = "1"
StaticArrays = "1"
Statistics = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
